name: Run Tests
on:
  push:
    branches:
      - master
    pull_request:
      - master
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World!
        run: echo "Hello World from an Action!"